# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d8ae1e68d8ba7d8690fb9f003a636b4a41e9fd79b7fb439bc198d6475df5fdc7aef8cf624ce17112a08bf07e24d18ca4d074b2777047061a8bfe28e38f5cc40

test:
  secret_key_base: 72639f794daf0ccf5f5a31cae56b4b0e0db3670cef63f4b574dd2f1f766907ec82a0843beb1c20c36e2196bfd24f3b384fde3302aaf08fb55c7f6738b9b3d251

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
